### ISSUE TITLE
Lack of information in annotations

### ISSUE THREAD

**Issue by IvanGarcia7** [RbnIzqGnl/PREVENTION-Toolkit#6]
Greetings. 

We are currently working on some developments related to the scope of your dataset and we are very interested in knowing more details to use and cite it.

The questions we have are the following in relation to the annotations:

1. The file "logs/log_ego_vehicle_vehicle.txt" contains information about the GPS coordinates, the speed of the vehicle as well as the time instances (Field 1 Timestamp and Field 2 GPSWritingTime). ¿How could we establish a relationship between this GPSWritingTime and each frame that composes the sequence? For example for the RECORD1 inside the file "logs/log_ego_vehicle.txt" the first field of the WritingTime is 0 but the first parameter of "logs/log_camera1.txt" is 40927637522.

2. The file "logs/log_ego_vehicle_vehicle.txt" contains information related to the speed ("EKF_speed"). From it is it possible for example to know the speed of the vehicle in km/s?

3. What are the parameters u and v in the file "detection_camera1/trajectories.txt"? Also, does x_cam or x_laser represent distances in meters?

4. We want to establish a correlation between the files "detection_camera1/detections_tracked.txt" with "detection_camera1/trajectories.txt". Initially, we thought it would be possible through the frame and the id's of each vehicle, however, the id's do not match. Is there any kind of connection?

Thanks in advance.

**Comment by RbnIzqGnl** [comment]
Dear IvanGarcia7, please find the answers to your questions below:

1. There is a GPS warm-up process, which is why there are some 0's in the field GPSWritingTime for some of the first entries. If you go to line 70 you can find the first sample with a valid GPSWritingTime (40832150, remember it is ms since the top of the day). Note that usually, the recording of the GPS starts before the recording of the video file.

2. The speed of the vehicle in the field EKF_speed is expressed in m/s. You can make the conversions you want. To convert to km/h (which I think you want) use 3.6 as the multiplier factor.

3. u and v are the pixel coordinates of the tracking point set into the vehicle in the image framework (2D). x, y, and z_cam are metric coordinates of the car in the camera reference system (3D). x, y, and z_lidar are metric coordinates in the lidar reference system (3D). Reference systems are visually explained here:
![image](https://user-images.githubusercontent.com/39160805/206698205-bb2e1e7e-2a18-4860-af3b-d7d0f25eff38.png)

4. There are two ids in the dataset. One for the detection files and the other for the labels file. For each frame, you can associate each id in "detection_camera1/trajectories.txt" with the ids in "detection_camera1/detections_tracked.txt" if the coordinate (u,v) in "detection_camera1/trajectories.txt" is inside the rectangle defined by (x_i, y_i, x_f, y_f) in "detection_camera1/detections_tracked.txt". Coordinate "u" is equivalent to "x" and "v" to "y" in the image plane. Basically, the condition is: x_i <= u <= x_f and y_i <= v <= y_f.

Hope you find these answers helpful for your developments.

**Comment by IvanGarcia7** [comment]
Thank you very much for your answer!. All questions have been correctly resolved.
